spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1
    username: sa
    password: sa
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false